<?php

namespace App\Console\Commands;

use App\Services\FormWOS\DeadstockExcelBackfillService;
use App\Services\FormWOS\DeadstockSnapshotImportService;
use Illuminate\Console\Command;

class BackfillDeadstockSnapshotsFromExcel extends Command
{
    protected $signature = 'deadstock:backfill-excel
        {--file= : Full path to one deadstock_YYYY-MM-DD.xlsx file}
        {--dir= : Directory containing deadstock_YYYY-MM-DD.xlsx files}
        {--date= : Import only one YYYY-MM-DD file from the directory}';

    protected $description = 'Backfill Deadstock review snapshots from historical Excel reports generated by mail-daily.';

    public function handle(
        DeadstockExcelBackfillService $excelService,
        DeadstockSnapshotImportService $importService
    ): int {
        $files = $this->resolveFiles();
        if ($files === []) {
            $this->error('No Deadstock Excel files matched the request.');
            return self::FAILURE;
        }

        $importedFiles = 0;
        $skippedFiles = 0;

        foreach ($files as $file) {
            try {
                $this->line('Processing ' . basename($file) . ' ...');
                $payload = $excelService->chunkedBackfill($file);
                $result = $importService->importItemChunks(
                    $payload['recv_date'],
                    $payload['as_of'],
                    $payload['generated'],
                    $payload['chunks']
                );
                $this->info(sprintf(
                    'Imported %s: %d items (%d created, %d updated)',
                    basename($file),
                    $result['items'],
                    $result['created'],
                    $result['updated']
                ));
                $importedFiles++;
            } catch (\Throwable $e) {
                $this->warn('Skipped ' . basename($file) . ': ' . $e->getMessage());
                $skippedFiles++;
            }
        }

        $this->line(sprintf('Backfill finished. Imported files: %d, skipped files: %d.', $importedFiles, $skippedFiles));

        return self::SUCCESS;
    }

    private function resolveFiles(): array
    {
        $file = trim((string) $this->option('file'));
        if ($file !== '') {
            return is_file($file) ? [$file] : [];
        }

        $dir = trim((string) $this->option('dir'));
        if ($dir === '') {
            $dir = 'C:\\Users\\nitiphan_tur\\mail-daily\\storage\\app\\public\\reports';
        }

        $date = trim((string) $this->option('date'));
        if ($date !== '') {
            $candidate = rtrim($dir, '\\/') . DIRECTORY_SEPARATOR . "deadstock_{$date}.xlsx";
            return is_file($candidate) ? [$candidate] : [];
        }

        $files = glob(rtrim($dir, '\\/') . DIRECTORY_SEPARATOR . 'deadstock_*.xlsx') ?: [];
        sort($files);

        return array_values(array_filter($files, fn(string $path) => is_file($path)));
    }
}
