@extends('layouts.layout')
@section('title','ประเภทการเบิกและ Lead Time')
@section('page-title','ประเภทการเบิกและ Lead Time')
@section('content')
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">กลุ่ม Part Number และ Lead Time</h4><div class="text-muted">F* = FG, R* = RM · วันทำงานจันทร์–เสาร์ · เก็บ Version ตาม Effective Date</div></div><a href="{{ route('stock-withdrawal.index') }}" class="btn btn-outline-primary">กลับรายการ</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('stock-withdrawal.types.store') }}" class="card card-body border-0 shadow-sm mb-3">@csrf<div class="row g-2 align-items-end"><div class="col-md-2"><label>Code</label><input name="code" class="form-control" required></div><div class="col-md-2"><label>ชื่อประเภท</label><input name="name" class="form-control" required></div><div class="col-md-2"><label>Lead Time (วัน)</label><input type="number" min="0" name="lead_time_days" class="form-control" required></div><div class="col-md-2"><label>เริ่มใช้</label><input type="date" name="effective_from" value="{{ now('Asia/Bangkok')->toDateString() }}" class="form-control" required></div><div class="col-md-2"><label>สิ้นสุด</label><input type="date" name="effective_to" class="form-control"></div><div class="col-md-1"><label>Active</label><select name="is_active" class="form-select"><option value="1">Yes</option><option value="0">No</option></select></div><div class="col-md-1"><button class="btn btn-primary w-100">เพิ่ม</button></div><div class="col-12"><label>หมายเหตุ</label><input name="remark" class="form-control"></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-sm mb-0"><thead class="table-light"><tr><th>Code</th><th>ประเภท</th><th>Lead Time</th><th>Effective</th><th>Active</th><th>หมายเหตุ</th></tr></thead><tbody>@foreach($types as $t)<tr><td>{{ $t->code }}</td><td>{{ $t->name }}</td><td>{{ $t->lead_time_days }} วัน</td><td>{{ $t->effective_from?->format('d/m/Y') }} - {{ $t->effective_to?->format('d/m/Y') ?: 'ต่อเนื่อง' }}</td><td>{{ $t->is_active?'Yes':'No' }}</td><td>{{ $t->remark }}</td></tr>@endforeach</tbody></table></div></div></div>
@endsection
