@extends('layouts.layout')
@section('title','แผนรายการเบิก')
@section('page-title','แผนรายการเบิก')
@section('content')
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">แผนรายการเบิก</h4><div class="text-muted">รายการที่บันทึกเพื่อเตรียมเบิกตามวันใช้งาน</div></div><div><a href="{{ route('stock-withdrawal.all-mfg') }}" class="btn btn-outline-primary">ดู MFG ทั้งหมด</a> <a href="{{ route('stock-withdrawal.create') }}" class="btn btn-primary">+ เพิ่มแผน</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<form class="card card-body border-0 shadow-sm mb-3"><div class="row g-2 align-items-end"><div class="col-md-2"><label>วันแจ้งเบิก</label><input type="date" name="date" value="{{ $filters['date']??'' }}" class="form-control"></div><div class="col-md-2"><label>โรงงาน</label><select name="site" class="form-select"><option value="">ทั้งหมด</option>@foreach(['WIRE','PLUS'] as $v)<option @selected(($filters['site']??'')===$v)>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><label>ประเภท</label><select name="type" class="form-select"><option value="">ทั้งหมด</option>@foreach($types as $t)<option value="{{ $t->code }}" @selected(($filters['type']??'')===$t->code)>{{ $t->name }}</option>@endforeach</select></div><div class="col-md-3"><label>MFG</label><input name="mfg" value="{{ $filters['mfg']??'' }}" class="form-control"></div><div class="col-md-3"><button class="btn btn-primary">ค้นหา</button> <a href="{{ route('stock-withdrawal.index') }}" class="btn btn-outline-secondary">ล้าง</a></div></div></form>
<div class="card border-0 shadow-sm"><div class="list-group list-group-flush">@forelse($plans as $plan)<div class="list-group-item p-3"><div class="row g-3"><div class="col-lg-3"><span class="badge bg-dark">{{ $plan->site }}</span> <strong>{{ $plan->mfg }}</strong><div class="text-primary">{{ $plan->partnumber }}</div><div class="small text-muted">{{ $plan->customer_name ?: '-' }}</div></div><div class="col-lg-2 small"><div>ขึ้นผลิต <strong>{{ $plan->production_date?->format('d/m/Y') }}</strong></div><div>ส่งมอบ {{ $plan->delivery_date?->format('d/m/Y') ?: '-' }}</div></div><div class="col-lg-7"><div class="d-flex flex-wrap gap-2">@foreach($plan->items as $item)<div class="border rounded px-3 py-2"><strong>{{ $item->type_name }}</strong><div class="small">เบิก {{ $item->planned_withdraw_date?->format('d/m/Y') }}</div><div class="{{ $item->day_offset < 0 ? 'text-danger fw-bold' : 'text-muted' }}">{{ $item->day_offset < 0 ? $item->day_offset.' วัน' : 'อีก '.$item->day_offset.' วัน' }}</div></div>@endforeach</div></div></div></div>@empty<div class="text-center text-muted py-5">ยังไม่มีแผนรายการเบิก</div>@endforelse</div></div><div class="mt-3">{{ $plans->links() }}</div></div>
@endsection
